'use client';

import ReactMarkdown from 'react-markdown';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { RefreshCcw } from 'lucide-react';

interface FeedbackDashboardProps {
  feedback: string;
  onRestart: () => void;
}

export function FeedbackDashboard({ feedback, onRestart }: FeedbackDashboardProps) {
  return (
    <div className="min-h-screen bg-background p-6 md:p-12 relative overflow-hidden">
      {/* Background decorations */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-primary/10 rounded-full blur-[150px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-purple-600/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-4xl mx-auto space-y-8 relative z-10">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Interview Feedback</h1>
            <p className="text-muted-foreground mt-1">Generated by your AI Coach based on the shadow evaluator's notes.</p>
          </div>
          <Button onClick={onRestart} variant="outline" className="gap-2 border-white/20 bg-black/40 hover:bg-black/60">
            <RefreshCcw size={16} />
            Start New Session
          </Button>
        </div>

        <Card className="glassmorphism border-white/10 shadow-xl overflow-hidden">
          <div className="h-2 w-full bg-gradient-to-r from-primary via-purple-500 to-blue-500" />
          <CardContent className="p-8">
            <article className="prose prose-invert prose-lg max-w-none">
              <ReactMarkdown>{feedback}</ReactMarkdown>
            </article>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
